### ISSUE TITLE
Can I verify webhook signature?

### ISSUE THREAD

**Issue by subhendukundu** [TrinaryLabs/stripe-workers#104]
```
    const _stripe = new Stripe(STRIPE_SECRET_KEY, { apiVersion: '2020-08-27' })
    const event = _stripe.webhooks.constructEvent(body, sig, STRIPE_WEBHOOK_SIGNING_SECRET)
```
I am trying to verify the signature. Can I do it with `stripe-workers`?

**Comment by EduM22** [comment]
This feature is not supported right now, I'am sorry.
You could use the the normal Stripe-node package to verify webhook events because that feature does not have any dependencies on node [Kristian Freemans code](https://blog.cloudflare.com/building-black-friday-e-commerce-experiences-with-jamstack-and-cloudflare-workers/) or you could use this [package](https://www.npmjs.com/package/@worker-tools/stripe-webhook).
